on:
  pull_request:
      branches: ["main"]
jobs:
  pr-workflow:
      runs-on: ubuntu-latest
      steps:
         # This step is required
          - name: checkout source
            uses: actions/checkout@master
            with:
              fetch-depth: 2  # Fetch enough history to compare commits

          - name: Calculate Next Version
            uses: ./
            id: versioning
            with:
              target-commit: ${{ github.event.pull_request.base.sha }}
              source-commit: ${{ github.event.pull_request.head.sha }}
              github-token: ${{ secrets.GH_TOKEN }}
              is-rc: "true" # Publish as a release candidate version
              is-draft: "true" # Publich as draft version
              build-metadata: ${{ github.workflow_sha }} # Optional build metadata
              create-tag: "false" # Don't create tag, only returns at output
              debug: "true" # Show debug messages

          - name: Show Output
            run: echo '${{ toJson(steps.versioning.outputs) }}'
